### ISSUE TITLE
Feria stopped working (multiple users)

### ISSUE THREAD

**Issue by gtrufitt** [guardian/feria#5] opened 2016-02-16 10:20 UTC
Myself and Nathaniel are seeing this error this morning.

```
Exception in thread "main" java.io.IOException: Cannot run program "": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
    at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:98)
    at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:112)
    at feria.Feria$$anonfun$run$1.apply(Feria.scala:55)
    at feria.Feria$$anonfun$run$1.apply(Feria.scala:54)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at feria.Feria$.run(Feria.scala:54)
    at feria.Feria$$anonfun$4.apply(Feria.scala:34)
    at feria.Feria$$anonfun$4.apply(Feria.scala:34)
    at scala.Option.map(Option.scala:146)
    at feria.Feria$.delayedEndpoint$feria$Feria$1(Feria.scala:34)
    at feria.Feria$delayedInit$body.apply(Feria.scala:15)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at feria.Feria$.main(Feria.scala:15)
    at feria.Feria.main(Feria.scala)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 22 more
```

cc/ @janua

**Comment by adamnfish** [comment] 2016-02-16 12:29
FYI there was [a (minor) change](https://github.com/guardian/janus/pull/224/files) to the credentials page in Janus yesterday. Although I can't see how it would be related?

**Comment by cb372** [comment] 2016-02-16 13:23
I can reproduce this. I think it must be caused by the change Adam mentioned, but I'm not sure why. I'll try to fix it after lunch.

**Comment by cb372** [comment] 2016-02-16 14:22
I've now fixed this. As expected, it was the change that Adam mentioned. I had to update the way Feria extracts the required commands from the Janus page.

Please do a `git pull` to upgrade Feria.

**Closed as completed by cb372** 2016-02-16 14:22 UTC

**Comment by gtrufitt** [comment] 2016-02-18 15:51
:+1: Thanks!
